### ISSUE TITLE
Matched cards animation

### ISSUE THREAD

**Issue by kovtun1** [foritari/Assignment4#2]
> 2. You must animate the following actions in your set game:
> c. the discovery of a match. matched cards should all fly away from where they were at the same time and bounce around on the screen for a couple of seconds before snapping to some “discard pile” somewhere on screen. the appearance of the discard pile is up to you.

> and bounce around on the screen for a couple of seconds

Please implement

> “discard pile”

Please add

**Comment by foritari** [comment]
https://github.com/foritari/Assignment4/pull/8
