### ISSUE TITLE
"At least the top card on the discard pile should be flipped face down"

### ISSUE THREAD

**Issue by kovtun1** [foritari/Assignment4#3]
> 2. You must animate the following actions in your set game:
> d. the flipping over of cards. cards should be dealt face down until they are in position, then they should be flipped over to reveal the set card contents and after cards have flown away to the discard pile, at least the top card on the discard pile should be flipped face down.

> after cards have flown away to the discard pile, at least the top card on the discard pile should be flipped face down.

Please implement

**Comment by foritari** [comment]
https://github.com/foritari/Assignment4/pull/8
